name: example
description: >
  The typesafe, reactive and lightweight SQLite abstraction for your Flutter applications.
  This is an example on how to use the library.
version: 1.0.0
homepage: https://amir-p.github.io/flat
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flat_orm:
    path: ../flat_orm/
  flutter:
    sdk: flutter

dev_dependencies:
  analyzer: ^5.0.0
  build_runner: ^2.1.7
  flat_generator:
    path: ../flat_generator/
  flutter_test:
    sdk: flutter
