name: flat_orm
description: >
  The typesafe, reactive, and lightweight SQLite abstraction for your Flutter applications.
  This library is the runtime dependency.
version: 1.5.0
homepage: https://amir-p.github.io/flat
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flat_annotation:
    path: ../flat_annotation/
  flutter:
    sdk: flutter
  meta: ^1.7.0
  path: ^1.8.0
  sqflite: ^2.0.0+4
  sqflite_common_ffi: ^2.0.0+3

dev_dependencies:
  build_runner: ^2.1.2
  collection: ^1.15.0
  flat_generator:
    path: ../flat_generator/
  flutter_test:
    sdk: flutter
  matcher: ^0.12.10
  mockito: ^5.0.15
